// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DragAndDropController from "./drag_and_drop_controller"
application.register("drag-and-drop", DragAndDropController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import NotificationToastController from "./notification_toast_controller"
application.register("notification-toast", NotificationToastController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)

import TaskCheckboxController from "./task_checkbox_controller"
application.register("task-checkbox", TaskCheckboxController)
